#!/usr/bin/env bash

echo 'viva_roles=router,vpnserver,dhcpserver,dhcprelay,radserver,tftpserver,bmrserver,iptvserver,gponserver,eponserver,statistic,brasserver,cmanager'
echo 'viva_roles_router=true'
echo 'viva_roles_vpnserver=false'
echo 'viva_roles_dhcpserver=false'
echo 'viva_roles_dhcprelay=true'
echo 'viva_roles_radserver=false'
echo 'viva_roles_tftpserver=false'
echo 'viva_roles_bmrserver=false'
echo 'viva_roles_iptvserver=false'
echo 'viva_roles_gponserver=false'
echo 'viva_roles_eponserver=false'
echo 'viva_roles_statistic=false'
echo 'viva_roles_brasserver=false'
echo 'viva_roles_cmanager=true'
